// Next Types & Fonts
import type { Metadata } from "next";
import { Alexandria } from "next/font/google";

// Global Styles
import "./globals.css";


const alexandria = Alexandria({
  variable: "--font-geist-alexandria",
  subsets: ["arabic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Moovy",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="ar" dir="rtl" className="dark">
      <body className={`${alexandria.className} antialiased overflow-x-hidden`} >
        {children}
      </body>
    </html>
  );
}
